### ISSUE TITLE
data attribution

### ISSUE THREAD

**Issue by k-dominik** [ilastik/cloud_ilastik#68]
cloud_ilastik currently features three public datasets from the knowledge graph:

* https://kg.ebrains.eu/search/instances/Dataset/9e96ebfa-3d18-43ac-977e-2eba89fa66ee
* https://kg.ebrains.eu/search/instances/Dataset/e15e4048955ed04112d2652d5a8ce587
* https://kg.ebrains.eu/search/instances/Dataset/eec5b03babebc54b64f6b31c3a87d92e

the source should be obvious when viewing datasets.

**Comment by Tomaz-Vieira** [comment]
I have a feeling that we should move away from 'hosting' the datasets and just allowing the user to enter the URLs of the datasets he's interested in. This would make life a bit harder on us since it wouldn't be trivial to figure out if some URL can be processed  by some .ilp project, but maybe we can leave such responsibility on the hands of the user. Alternatively, we could have some `DataSource` implementations also available on cloud-ilastik, so that it can 'connect' to the user's URL, check dimensionalities and fail faster in case of bad data
